### ISSUE TITLE
buildout failure on OS X El Capitan

### ISSUE THREAD

**Issue by zhaoyue-zephyrus** [bioidiap/bob.bio.spear#11]
Hi all,

I am trying to install bob.bio.spear on OS X El Capitan but meet some problems.

I am used  to Anaconda so I created a conda environment following [https://github.com/idiap/bob/wiki/Installation-with-conda](url). Then in the newly created environment, I cloned this repo and run "python bootstrap-buildout.py" and "./bin/buildout". The log looks like

...
Develop: '/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core'
bob.buildout.tools: taking requirement `setuptools' (23.0.0) from `/Users/zhaoyue/workspace/bob.bio.spear/eggs/setuptools-23.0.0-py2.7.egg'
bob.buildout.tools: taking requirement `bob.extension' (2.2.1b0) from `/Users/zhaoyue/workspace/bob.bio.spear/src/bob.extension'
bob.buildout.tools: taking requirement `bob.blitz' (2.0.9b0) from `/Users/zhaoyue/workspace/bob.bio.spear/src/bob.blitz'
Traceback (most recent call last):
  File "/var/folders/rr/wl535zcx1bnbl0vs3b8h14l00000gp/T/tmppanFll", line 14, in <module>
    exec(compile(open('/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/setup.py').read(), '/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/setup.py', 'exec'))
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/setup.py", line 8, in <module>
    from bob.blitz.extension import Extension, Library, build_ext
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.blitz/bob/blitz/__init__.py", line 6, in <module>
    from ._library import array, as_blitz
ImportError: dlopen(/Users/zhaoyue/workspace/bob.bio.spear/src/bob.blitz/bob/blitz/_library.so, 2): Library not loaded: @rpath/libblitz.0.dylib
  Referenced from: /Users/zhaoyue/workspace/bob.bio.spear/src/bob.blitz/bob/blitz/_library.so
  Reason: image not found
While:
  Installing.
  Processing develop directory '/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/bob.buildout-2.0.11-py2.7.egg/bob/buildout/extension.py", line 213, in develop
    zc.buildout.easy_install.call_subprocess(args)
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/Users/zhaoyue/anaconda/envs/bob_env_py27/bin/python', '/var/folders/rr/wl535zcx1bnbl0vs3b8h14l00000gp/T/tmppanFll', '-v', 'develop', '-mxN', '-d', '/Users/zhaoyue/workspace/bob.bio.spear/develop-eggs/tmphtwg0Lbuild'

Seems like some libraries are missing? Can anyone offer some advice? Thanks in advance!

**Comment by 183amir** [comment]
Hi @zhaoyue-zephyrus This is a general issue and not related to `bob.bio.spear`. While it should not happen, this is a linking problem which could possibly come from `bob.buildout` or `bob.extension`.
To avoid it try this:
```sh
$ DYLD_FALLBACK_LIBRARY_PATH=/Users/zhaoyue/anaconda/envs/bob_env_py27/lib ./bin/buildout
$ # Assuming "/Users/zhaoyue/anaconda/envs/bob_env_py27" is your environment path.
```

**Comment by zhaoyue-zephyrus** [comment]
Hi @183amir Thanks for your reply! I tried it and now another problem arises.

> ......(looking good)
 Develop: '/Users/zhaoyue/workspace/bob.bio.spear/src/bob.io.base'
bob.buildout.tools: taking requirement `bob.extension' (2.2.1b0) from `/Users/zhaoyue/workspace/bob.bio.spear/src/bob.extension'
bob.buildout.tools: taking requirement `bob.blitz' (2.0.9b0) from `/Users/zhaoyue/workspace/bob.bio.spear/src/bob.blitz'
bob.buildout.tools: taking requirement `bob.core' (2.1.3a0) from `/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core'
Traceback (most recent call last):
  File "/var/folders/rr/wl535zcx1bnbl0vs3b8h14l00000gp/T/tmpeKuy6i", line 14, in <module>
    exec(compile(open('/Users/zhaoyue/workspace/bob.bio.spear/src/bob.io.base/setup.py').read(), '/Users/zhaoyue/workspace/bob.bio.spear/src/bob.io.base/setup.py', 'exec'))
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.io.base/setup.py", line 178, in <module>
    boost_modules = boost_modules,
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.blitz/bob/blitz/extension.py", line 52, in __init__
    BobExtension.__init__(self, *args, **kwargs)
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.extension/bob/extension/__init__.py", line 294, in __init__
    bob_includes, bob_libraries, bob_library_dirs, bob_macros = get_bob_libraries(self.bob_packages)
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.extension/bob/extension/__init__.py", line 186, in get_bob_libraries
    pkg = importlib.import_module(package)
  File "/Users/zhaoyue/anaconda/envs/bob_env_py27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/bob/core/__init__.py", line 6, in <module>
    from . import log
  File "/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/bob/core/log.py", line 11, in <module>
    from ._logging import reset
ImportError: dlopen(/Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/bob/core/_logging.so, 2): Symbol not found: __ZN3bob4core16AutoOutputDeviceC1ERKSs
  Referenced from: /Users/zhaoyue/workspace/bob.bio.spear/src/bob.core/bob/core/_logging.so
  Expected in: dynamic lookup

While:
  Installing.
  Processing develop directory '/Users/zhaoyue/workspace/bob.bio.spear/src/bob.io.base'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/bob.buildout-2.0.11-py2.7.egg/bob/buildout/extension.py", line 213, in develop
    zc.buildout.easy_install.call_subprocess(args)
  File "/Users/zhaoyue/workspace/bob.bio.spear/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/Users/zhaoyue/anaconda/envs/bob_env_py27/bin/python', '/var/folders/rr/wl535zcx1bnbl0vs3b8h14l00000gp/T/tmpeKuy6i', '-v', 'develop', '-mxN', '-d', '/Users/zhaoyue/workspace/bob.bio.spear/develop-eggs/tmpMWn9Ubbuild'

**Comment by 183amir** [comment]
@zhaoyue-zephyrus you are facing an ABI incompatibility issue.
Please post your problem on our mailing list: https://groups.google.com/forum/?fromgroups#!forum/bob-devel
Also, attach the full log not just parts of it.
I would start compiling everything again in a fresh folder to see if your problem will be fixed.

**Comment by zhaoyue-zephyrus** [comment]
Hi, @183amir ! I did not go into it further since I switched to the a Ubuntu server and it worked well. :-)

**Comment by 183amir** [comment]
okay then I will close this.
