### ISSUE TITLE
Failure in running baseline experiments

### ISSUE THREAD

**Issue by suzinia** [bioidiap/bob.bio.spear#12]
Hello,

I am running the baseline experiments with voxforge in the link;
https://pythonhosted.org/bob.bio.spear/baselines.html

I was able to run the first baseline experiment which was
$ bin/verify.py  -d voxforge -p energy-2gauss -e mfcc-60 -a gmm-voxforge -s ubm_gmm --groups {dev,eval}

However, the others failed with the following error message.

$ bin/verify.py  -d voxforge -p energy-2gauss -e mfcc-60 -a ivec-plda-voxforge -s ivec-plda --groups {dev,eval} -g grid

bob.bio.base@2016-06-23 21:09:38,763 -- ERROR: During the execution, an exception was raised: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bin/verify.py", line 34, in <module>
    sys.exit(bob.bio.base.script.verify.main())
  File "/home/soo/work/eggs/bob.bio.base-2.0.9-py2.7.egg/bob/bio/base/script/verify.py", line 446, in main
    verify(args, command_line_parameters)
  File "/home/soo/work/eggs/bob.bio.base-2.0.9-py2.7.egg/bob/bio/base/script/verify.py", line 399, in verify
    retval = add_jobs(args, submitter)
  File "/home/soo/work/eggs/bob.bio.base-2.0.9-py2.7.egg/bob/bio/base/script/verify.py", line 57, in add_jobs
    **args.grid.preprocessing_queue)
  File "/home/soo/work/eggs/bob.bio.base-2.0.9-py2.7.egg/bob/bio/base/tools/grid.py", line 111, in submit
    **kwargs
  File "/home/soo/work/eggs/gridtk-1.3.0-py2.7.egg/gridtk/sge.py", line 98, in submit
    job_id = self._submit_to_grid(job, name, array, dependencies, log_dir, verbosity, **kwargs)
  File "/home/soo/work/eggs/gridtk-1.3.0-py2.7.egg/gridtk/sge.py", line 64, in _submit_to_grid
    grid_id = qsub(command, context=self.context, name=name, deps=deps, array=q_array, stdout=log_dir, stderr=log_dir, **kwargs)
  File "/home/soo/work/eggs/gridtk-1.3.0-py2.7.egg/gridtk/tools.py", line 255, in qsub
    jobid = str_(sexec(context, scmd))
  File "/home/soo/work/eggs/gridtk-1.3.0-py2.7.egg/gridtk/setshell.py", line 104, in sexec
    stderr=subprocess.STDOUT, env=E)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Thank you!

**Comment by tiagofrepereira2012** [comment]
I don't know if it is a déjà vu or if it is the same person, but I just replied this on bob-devel (google groups).

Just pasting the message from there and closing the issue

cheers
-----

Try to remove the argument `-g grid` in your command line.
The command as it is, tries to submit a job in the IDIAP cluster

The command below may work

**Comment by suzinia** [comment]
Sorry,
I indeed posted it there, too.

Thank you for the response. It seems working now :)
