### ISSUE TITLE
 unpack requires a string argument of length 4 - broken wave files?

### ISSUE THREAD

**Issue by 1kastner** [bioidiap/bob.bio.spear#6]
I guess the problem is related to a damaged wave files. I downloaded voxforge but because of difficulties I guess some of them are broken. However, I can't see with this error message which part is broken.

marvin@marvin-VirtualBox:~/Downloads/bob-2.0.6$ python ~/Downloads/bob-2.0.6/bin/verify.py  -d voxforge -p energy-2gauss -e mfcc-60 -a gmm-voxforge -s ubm_gmm --groups {dev,eval}
/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
bob.bio.base@2015-12-27 22:26:29,894 -- ERROR: During the execution, an exception was raised: unpack requires a string argument of length 4
Traceback (most recent call last):
  File "/home/marvin/Downloads/bob-2.0.6/bin/verify.py", line 56, in <module>
    sys.exit(bob.bio.base.script.verify.main())
  File "/home/marvin/Downloads/bob-2.0.6/eggs/bob.bio.base-2.0.4-py2.7.egg/bob/bio/base/script/verify.py", line 435, in main
    verify(args, command_line_parameters)
  File "/home/marvin/Downloads/bob-2.0.6/eggs/bob.bio.base-2.0.4-py2.7.egg/bob/bio/base/script/verify.py", line 415, in verify
    if not execute(args):
  File "/home/marvin/Downloads/bob-2.0.6/eggs/bob.bio.base-2.0.4-py2.7.egg/bob/bio/base/script/verify.py", line 255, in execute
    force = args.force)
  File "/home/marvin/Downloads/bob-2.0.6/eggs/bob.bio.base-2.0.4-py2.7.egg/bob/bio/base/tools/preprocessor.py", line 59, in preprocess
    data = preprocessor.read_original_data(file_name)
  File "/home/marvin/Downloads/bob-2.0.6/eggs/bob.bio.spear-2.0.4-py2.7.egg/bob/bio/spear/preprocessor/Base.py", line 21, in read_original_data
    rate, audio = scipy.io.wavfile.read(original_file_name)
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 173, in read
    _skip_unknown_chunk(fid)
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 90, in _skip_unknown_chunk
    size = struct.unpack(fmt, data)[0]
struct.error: unpack requires a string argument of length 4

**Comment by siebenkopf** [comment]
Have you tried to download the data again? AFAIK, with correct data, we do not obtain this kind of problems. 

Anyways, it is not one of Bob's functions failing, but the one from ``scipy``. Hence, we cannot do anything about this.
